version: '3.7'
services:

  server:
    image: elasticscripts_server:v1.2
    ports:
      - "5000:5000"
    links:
      - "elasticsearch:es"
    networks:
      - clir_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    tty: true
    environment:
      discovery.type: single-node
    networks:
      - clir_network

  redis:
    image: "redis:alpine"
    networks:
      - clir_network

networks:
  clir_network:
    name: elasticscripts_default
    driver: bridge

volumes:
  es-data:
    driver: local
